mqtt:
  brokerUrl : mqtt://192.168.1.33
  baseTopic: sia2mqtt

sia:
  port: 10500
  hostname: 192.168.1.33

zones:
  1021:
    name: front_door
    handler: door

  1018:
    name: office_pir
    handler: pir
